### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by ik04** [ik04/Yt-to-mp3#1]
- [x] finish the results section
- [x] alter sonner colours to make em cooler
- [x] add loading sonner for conversion
- [x] display result and smooth scroll to it 
- [x] add ghosts
- [x] add the footer
- [x] make the site responsive
- [x] add yt music support
